-- ==========================================================
-- WARNING: Auto-generated schema. Review before using in production.
-- ==========================================================
-- Generated by IdeiaEstruturada from Idea Pack
-- Project: CuidaFarma
-- Generated at: 2026-03-19T19:10:21.158Z
-- Entities: 1
-- ==========================================================

-- Trigger function for updated_at
CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- Table: usuarios (from Entity: Usuário)
-- Representa um usuário do sistema, que pode ser farmacêutico ou administrador, com controle de acesso e autenticação.
-- ============================================
CREATE TABLE IF NOT EXISTS usuarios (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nome TEXT NOT NULL,
  login TEXT NOT NULL,
  senha TEXT NOT NULL,
  perfil TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER set_usuarios_updated_at
  BEFORE UPDATE ON usuarios
  FOR EACH ROW
  EXECUTE FUNCTION trigger_set_updated_at();
